### ISSUE TITLE
Not doing a loop in stan-nc

### ISSUE THREAD

**Issue by SteveBronder** [hdarjus/SV-comparison#1]
Hello! I'm kind of confused by the loop here in stan-nc

```stan
  for (i in 1:N) {
    if (i == 1) {
      h_i_mean[i] = 0;
      h_i_sigma[i] = pow(1-square(phi), -0.5);
    } else {
      h_i_mean[i] = fma(phi, h[i-1], 0);
      h_i_sigma[i] = 1;
    }
    exph[i] = exp(fma(h[i], 0.5*sigma, 0.5*mu));
  }
```

I thought stoch vol models have to depend on previous points of `h`, but it appears you've written this in a way that could actually be fully vectorized like the below for a good bit of speedup

```stan
data {
  int<lower=0> N;
  real y[N];
}

transformed data {
  real<lower=0> phi_prior_a = 1;
  real<lower=0> phi_prior_b = 1;
  real mu_prior_mu = 0;
  real<lower=0> mu_prior_sigma = 100;
  real<lower=0> sigma_prior_shape = 0.5;
  real<lower=0> sigma_prior_rate = 0.5;
}

parameters {
  vector[N] h;
  real<lower=0,upper=1> phi_beta;
  real mu;
  real<lower=0> sigma2;
}

transformed parameters {
  real<lower=-1,upper=1> phi = fma(phi_beta, 2, -1);
  real<lower=0> sigma = sqrt(sigma2);
  vector[N] h_i_mean;
  vector<lower=0>[N] h_i_sigma;
  h_i_mean[1] = 0;
  h_i_sigma[1] = pow(1 - square(phi), -0.5);
  h_i_sigma[2:N] = rep_vector(1, (N - 1));
  h_i_mean[2:N] = phi * h[1:(N-1)]; // This added 0 before, but idt that's needed?
}

model {
  mu ~ normal(mu_prior_mu, mu_prior_sigma);
  phi_beta ~ beta(phi_prior_a, phi_prior_b);
  sigma2 ~ gamma(sigma_prior_shape, sigma_prior_rate);

  h ~ normal(h_i_mean, h_i_sigma);
  y ~ normal(0, exp(h * (0.5 * sigma) + (0.5 * mu)));
}
```

But, is this correct? Looking at the stoch vol model from the Stan docs [here](https://mc-stan.org/docs/2_22/stan-users-guide/stochastic-volatility-models.html) it seems like you do need a loop to be updating off of past values of `h`. Is there a paper somewhere or an explainer on how this model avoids the time dependence? If this does work that would be super awesome as we will have a new matrix type soon in stan that would make this very fast

**Comment by hdarjus** [comment]
Hi @SteveBronder,

This was a long time ago :)
I checked the link and I don't really see the difference here. The dependency graph between the `h` variables is the same in my code and in the mc-stan documentation, isn't it? I just put the mean into a separate computation.
Let me know what you think.

Can one do a "Getting it right"-type [1] of test with Stan? I think if you compare my Stan output with another representation of the model, they should give the same. I think I tested these thoroughly against other implementations.

I recommend this article about parameterizations of the vanilla SV model: [3].
If you find that interesting, I recommend you my follow-up project on SV parameterization [2].

Thanks.

References:
[1] DOI: [10.1198/016214504000001132](https://doi.org/10.1198/016214504000001132)
[2] DOI: [10.1007/978-3-030-30611-3_8](https://doi.org/10.1007/978-3-030-30611-3_8)
[3] DOI: [10.1016/j.csda.2013.01.002](https://doi.org/10.1016/j.csda.2013.01.002)
